### PR TITLE
heavy refactoring

### PR DESCRIPTION
**Pull request by nazarpechka**
python3, httplib2, better performance

### CODE REVIEW

**Comment by roma323** [comment]
`while True:
    pass` not needed

**Comment by nazarpechka** [comment]
@roma323 threads stop without while

**Comment by roma323** [comment]
what? this code working without while True

**Comment by nazarpechka** [comment]
image

**Comment by roma323** [comment]
ok. but you have additional tabs  14-17 lines

**Comment by nazarpechka** [comment]
fixed already, let me only push it

**Comment by roma323** [comment]
where is support GIF, PNG format?

**Comment by markbookk** [comment]
Thanks for the help. I added the script to the repository.

**Pull request closed without merging**
